locals {
  grafana_labels = {
    "app.kubernetes.io/name"       = "grafana"
    "app.kubernetes.io/component"  = "visualization"
    "app.kubernetes.io/part-of"    = "autoscaling-demo"
    "app.kubernetes.io/managed-by" = "terraform"
  }

  grafana_dashboard = {
    annotations = {
      list = []
    }
    editable      = false
    graphTooltip  = 1
    id            = null
    refresh       = "5s"
    schemaVersion = 41
    tags          = ["kind", "hpa", "k6"]
    time = {
      from = "now-15m"
      to   = "now"
    }
    timezone = "browser"
    title    = "HPA Autoscaling Lab"
    uid      = "hpa-autoscaling"
    version  = 1

    panels = [
      {
        type        = "timeseries"
        title       = "k6 generated request rate"
        description = "Requests per second generated by the in-cluster k6 Job."
        datasource = {
          type = "prometheus"
          uid  = "prometheus"
        }
        gridPos = { h = 8, w = 12, x = 0, y = 0 }
        targets = [{
          expr         = "sum(rate(k6_http_reqs_total[15s]))"
          legendFormat = "k6 requests/sec"
          refId        = "A"
        }]
        fieldConfig = {
          defaults  = { unit = "reqps", min = 0 }
          overrides = []
        }
        options = {
          legend  = { displayMode = "table", placement = "bottom", calcs = ["mean", "max"] }
          tooltip = { mode = "multi", sort = "desc" }
        }
      },
      {
        type        = "timeseries"
        title       = "Web requests served"
        description = "Successful request rate summed across all Ready web Pods."
        datasource = {
          type = "prometheus"
          uid  = "prometheus"
        }
        gridPos = { h = 8, w = 12, x = 12, y = 0 }
        targets = [{
          expr         = "sum(rate(web_requests_total{status=\"2xx\"}[15s]))"
          legendFormat = "served requests/sec"
          refId        = "A"
        }]
        fieldConfig = {
          defaults  = { unit = "reqps", min = 0 }
          overrides = []
        }
        options = {
          legend  = { displayMode = "table", placement = "bottom", calcs = ["mean", "max"] }
          tooltip = { mode = "multi", sort = "desc" }
        }
      },
      {
        type        = "timeseries"
        title       = "HPA CPU utilization"
        description = "Average Go process CPU divided by the 200m CPU request used by HPA."
        datasource = {
          type = "prometheus"
          uid  = "prometheus"
        }
        gridPos = { h = 8, w = 12, x = 0, y = 8 }
        targets = [
          {
            expr         = "avg(rate(process_cpu_seconds_total{job=\"web\"}[30s])) / 0.2 * 100"
            legendFormat = "average utilization"
            refId        = "A"
          },
          {
            expr         = "vector(50)"
            legendFormat = "HPA target"
            refId        = "B"
          },
        ]
        fieldConfig = {
          defaults  = { unit = "percent", min = 0 }
          overrides = []
        }
        options = {
          legend  = { displayMode = "table", placement = "bottom", calcs = ["mean", "max"] }
          tooltip = { mode = "multi", sort = "desc" }
        }
      },
      {
        type        = "timeseries"
        title       = "HPA replicas"
        description = "Desired and current replica history from kube-state-metrics."
        datasource = {
          type = "prometheus"
          uid  = "prometheus"
        }
        gridPos = { h = 8, w = 12, x = 12, y = 8 }
        targets = [
          {
            expr         = "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"${var.namespace}\",horizontalpodautoscaler=\"web\"}"
            legendFormat = "current replicas"
            refId        = "A"
          },
          {
            expr         = "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"${var.namespace}\",horizontalpodautoscaler=\"web\"}"
            legendFormat = "desired replicas"
            refId        = "B"
          },
        ]
        fieldConfig = {
          defaults  = { decimals = 0, min = 0 }
          overrides = []
        }
        options = {
          legend  = { displayMode = "table", placement = "bottom", calcs = ["lastNotNull", "max"] }
          tooltip = { mode = "multi", sort = "desc" }
        }
      },
      {
        type        = "timeseries"
        title       = "Web CPU by Pod"
        description = "CPU core percentage for each independently scraped web Pod."
        datasource = {
          type = "prometheus"
          uid  = "prometheus"
        }
        gridPos = { h = 8, w = 12, x = 0, y = 16 }
        targets = [{
          expr         = "rate(process_cpu_seconds_total{job=\"web\"}[30s]) * 100"
          legendFormat = "{{pod}}"
          refId        = "A"
        }]
        fieldConfig = {
          defaults  = { unit = "percent", min = 0 }
          overrides = []
        }
        options = {
          legend  = { displayMode = "table", placement = "bottom", calcs = ["mean", "max"] }
          tooltip = { mode = "multi", sort = "desc" }
        }
      },
      {
        type        = "timeseries"
        title       = "Web p95 request duration"
        description = "Server-side p95 latency across all web replicas."
        datasource = {
          type = "prometheus"
          uid  = "prometheus"
        }
        gridPos = { h = 8, w = 12, x = 12, y = 16 }
        targets = [{
          expr         = "histogram_quantile(0.95, sum by (le) (rate(web_request_duration_seconds_bucket[30s])))"
          legendFormat = "p95 duration"
          refId        = "A"
        }]
        fieldConfig = {
          defaults  = { unit = "s", min = 0 }
          overrides = []
        }
        options = {
          legend  = { displayMode = "table", placement = "bottom", calcs = ["mean", "max"] }
          tooltip = { mode = "multi", sort = "desc" }
        }
      },
    ]
  }
}

resource "kubernetes_config_map_v1" "grafana_provisioning" {
  metadata {
    name      = "grafana-provisioning"
    namespace = kubernetes_namespace_v1.web.metadata[0].name
  }

  data = {
    "datasource.yaml" = <<-YAML
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: prometheus
          type: prometheus
          access: proxy
          url: http://prometheus.${var.namespace}.svc.cluster.local:9090
          isDefault: true
          editable: false
          jsonData:
            timeInterval: 5s
    YAML

    "dashboard-provider.yaml" = <<-YAML
      apiVersion: 1
      providers:
        - name: autoscaling-lab
          orgId: 1
          folder: Kubernetes Labs
          type: file
          disableDeletion: true
          editable: false
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards
    YAML
  }
}

resource "kubernetes_config_map_v1" "grafana_dashboard" {
  metadata {
    name      = "grafana-dashboard"
    namespace = kubernetes_namespace_v1.web.metadata[0].name
  }

  data = {
    "hpa-autoscaling.json" = jsonencode(local.grafana_dashboard)
  }
}

resource "kubernetes_deployment_v1" "grafana" {
  metadata {
    name      = "grafana"
    namespace = kubernetes_namespace_v1.web.metadata[0].name
    labels    = local.grafana_labels
  }

  wait_for_rollout = true

  spec {
    replicas = 1

    selector {
      match_labels = local.grafana_labels
    }

    template {
      metadata {
        labels = local.grafana_labels

        annotations = {
          "lab.example.com/provisioning-hash" = sha256(join("", values(kubernetes_config_map_v1.grafana_provisioning.data)))
          "lab.example.com/dashboard-hash"    = sha256(kubernetes_config_map_v1.grafana_dashboard.data["hpa-autoscaling.json"])
        }
      }

      spec {
        automount_service_account_token = false

        security_context {
          run_as_non_root = true
          run_as_user     = 472
          run_as_group    = 472
          fs_group        = 472

          seccomp_profile {
            type = "RuntimeDefault"
          }
        }

        container {
          name  = "grafana"
          image = var.grafana_image

          env {
            name  = "GF_AUTH_ANONYMOUS_ENABLED"
            value = "true"
          }

          env {
            name  = "GF_AUTH_ANONYMOUS_ORG_ROLE"
            value = "Viewer"
          }

          env {
            name  = "GF_AUTH_DISABLE_LOGIN_FORM"
            value = "true"
          }

          env {
            name  = "GF_USERS_ALLOW_SIGN_UP"
            value = "false"
          }

          env {
            name  = "GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH"
            value = "/var/lib/grafana/dashboards/hpa-autoscaling.json"
          }

          # This lab only uses Grafana's built-in Prometheus data source and
          # time-series panels. Avoid downloading optional plugins at startup.
          env {
            name  = "GF_PLUGINS_PREINSTALL_DISABLED"
            value = "true"
          }

          env {
            name  = "GF_ANALYTICS_REPORTING_ENABLED"
            value = "false"
          }

          env {
            name  = "GF_ANALYTICS_CHECK_FOR_UPDATES"
            value = "false"
          }

          env {
            name  = "GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES"
            value = "false"
          }

          port {
            name           = "http"
            container_port = 3000
          }

          resources {
            requests = {
              cpu    = "100m"
              memory = "128Mi"
            }

            limits = {
              cpu    = "300m"
              memory = "512Mi"
            }
          }

          readiness_probe {
            http_get {
              path = "/api/health"
              port = "http"
            }

            period_seconds  = 5
            timeout_seconds = 2
          }

          liveness_probe {
            http_get {
              path = "/api/health"
              port = "http"
            }

            period_seconds    = 10
            timeout_seconds   = 2
            failure_threshold = 3
          }

          security_context {
            allow_privilege_escalation = false

            capabilities {
              drop = ["ALL"]
            }
          }

          volume_mount {
            name       = "datasources"
            mount_path = "/etc/grafana/provisioning/datasources"
            read_only  = true
          }

          volume_mount {
            name       = "dashboard-provider"
            mount_path = "/etc/grafana/provisioning/dashboards"
            read_only  = true
          }

          volume_mount {
            name       = "dashboard"
            mount_path = "/var/lib/grafana/dashboards"
            read_only  = true
          }

          volume_mount {
            name       = "data"
            mount_path = "/var/lib/grafana"
          }
        }

        volume {
          name = "datasources"

          config_map {
            name = kubernetes_config_map_v1.grafana_provisioning.metadata[0].name
            items {
              key  = "datasource.yaml"
              path = "datasource.yaml"
            }
          }
        }

        volume {
          name = "dashboard-provider"

          config_map {
            name = kubernetes_config_map_v1.grafana_provisioning.metadata[0].name
            items {
              key  = "dashboard-provider.yaml"
              path = "dashboard-provider.yaml"
            }
          }
        }

        volume {
          name = "dashboard"

          config_map {
            name = kubernetes_config_map_v1.grafana_dashboard.metadata[0].name
          }
        }

        volume {
          name = "data"

          empty_dir {}
        }
      }
    }
  }
}

resource "kubernetes_service_v1" "grafana" {
  metadata {
    name      = "grafana"
    namespace = kubernetes_namespace_v1.web.metadata[0].name
    labels    = local.grafana_labels
  }

  spec {
    selector = local.grafana_labels

    port {
      name        = "http"
      port        = 3000
      target_port = "http"
    }

    type = "ClusterIP"
  }
}
